language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

env:
  - GO111MODULE=on

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - go get -v golang.org/x/lint/golint

script:
  - golint -set_exit_status ./...
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
